work_dir: ./work_dir/ntu/xview/dgnn_test_motion
model_saved_name: ./runs/ntu_cs_dgnn_test_motion

# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  joint_data_path: ./data/ntu/xview/val_data_joint_motion.npy
  bone_data_path: ./data/ntu/xview/val_data_bone_motion.npy
  label_path: ./data/ntu/xview/val_label.pkl
  debug: False

# model
model: model.dgnn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.directed_ntu_rgb_d.Graph

# test
phase: test
device: [0]
test_batch_size: 32
# NOTE: default tests the newest weight
# Change filename if using different batch sizes
weights: ./runs/ntu_cs_dgnn_motion-49-62600.pt
save_score: True # True for performing 2-stream fusion
