work_dir: ./work_dir/ntu/xsub/dgnn_spatial
model_saved_name: ./runs/ntu_cs_dgnn_spatial
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  joint_data_path: ./data/ntu/xsub/train_data_joint.npy
  bone_data_path: ./data/ntu/xsub/train_data_bone.npy
  label_path: ./data/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  joint_data_path: ./data/ntu/xsub/val_data_joint.npy
  bone_data_path: ./data/ntu/xsub/val_data_bone.npy
  label_path: ./data/ntu/xsub/val_label.pkl

# model
model: model.dgnn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.directed_ntu_rgb_d.Graph
  # graph_args:
  #   labeling_mode: 'spatial'

# optim
weight_decay: 0.0005
base_lr: 0.1
step: [60, 90]

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 120
nesterov: True
freeze_graph_until: 10  # Number of epochs until graphs can be updated

